### ISSUE TITLE
Loading atomiccaldera as plugin failed with ModuleNotFoundError

### ISSUE THREAD

**Issue by pe3zx** [xenoscr/atomiccaldera#13]
Hi @xenoscr, thank you for a wonderful project.

I tried to deploy `atomiccaldera` with the instruction appeared on `README.md`. By the way, after finished adding `atomiccaldera` to `caldera/default.py` and trying to run, I encountered the following `ModuleNotFoundError` error:

```
(caldera) $ python server.py
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Loading plugin: atomiccaldera
Traceback (most recent call last):
  File "server.py", line 100, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 42, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/home/user/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/caldera/plugins/atomiccaldera/hook.py", line 19, in <module>
    from plugins.atomiccaldera.app.ac_database import ACDatabase
  File "/home/user/caldera/plugins/atomiccaldera/app/ac_database.py", line 18, in <module>
    from app.service.base_service import BaseService
ModuleNotFoundError: No module named 'app.service.base_service'
(caldera) $
```

The environment is **Python 3.8.0** with the same virtualenv used by Caldera. Not sure that this problem relating to 3.8.0, but will try to run again with a downgrade version.

Thank you for your support.

**Comment by Roslekas** [comment]
Hi, same error with python 3.7.5
[.....]
ERROR:root:Error importing plugin=atomiccaldera, No module named 'app.service.base_service'
ERROR:root:Error loading plugin=atomiccaldera, 'NoneType' object has no attribute 'description'
[....]
ERROR:root:Error importing plugin=atomiccaldera, No module named 'app.service.base_service'
ERROR:root:Error enabling plugin=atomiccaldera, 'NoneType' object has no attribute 'enable'
[....]
Would be nice to have it fixed:)

**Comment by OmarDarwish** [comment]
There seems to be an issue loading `app.utilitiy.logger` as well:

```
2020-04-03 04:40:00 - ERROR (c_plugin.py:69 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2020-04-03 04:40:00 - ERROR (c_plugin.py:44 load) Error loading plugin=atomiccaldera, 'NoneType' object has no attribute 'description'
2020-04-03 04:40:01 - ERROR (data_svc.py:346 _verify_ability_set) Fix technique ID for ability: 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
2020-04-03 04:40:01 - ERROR (data_svc.py:346 _verify_ability_set) Fix technique ID for ability: 13d0d9cf-e31a-47b6-9217-f38e3f7c25ef
2020-04-03 04:40:01 - ERROR (data_svc.py:346 _verify_ability_set) Fix technique ID for ability: 90418255-b202-4fc3-b0ea-b105bff39ca5
2020-04-03 04:40:01 - ERROR (data_svc.py:346 _verify_ability_set) Fix technique ID for ability: 90418255-b202-4fc3-b0ea-b105bff39ca5
```

This is with version 2.6.6 of caldera

**Comment by netnhunt** [comment]
There is an issue in loading app.utility.logger with Caldera 2.6.0

2020-04-25 06:55:23 - ERROR (c_plugin.py:69 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2020-04-25 06:55:23 - ERROR (c_plugin.py:44 load) Error loading plugin=atomiccaldera, 'NoneType' object has no attribute 'description'
2020-04-25 06:55:23 - ERROR (c_plugin.py:69 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2020-04-25 06:55:23 - ERROR (c_plugin.py:55 enable) Error enabling plugin=atomiccaldera, 'NoneType' object has no attribute 'enable'

**Comment by Michealpool** [comment]
i am also facingsame error.

ERROR (c_plugin.py:94 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2020-06-25 09:10:57 - ERROR (c_plugin.py:60 load_plugin) Error loading plugin=atomiccaldera, 'NoneType' object has no attribute 'description'
2020-06-25 09:10:57 - ERROR (c_plugin.py:94 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2020-06-25 09:10:57 - ERROR (c_plugin.py:71 enable) Error enabling plugin=atomiccaldera, 'NoneType' object has no attribute 'enable'

**Comment by elruedas-ops** [comment]
Hi. Same issue.

Caldera and atomiccaldera latest versions (all installed as root with sudo).

===========================================
2021-01-05 13:28:44 - WARNING (server.py:83 <module>) --insecure flag set. Caldera will use the default.yml config file.
2021-01-05 13:28:44 - INFO  (server.py:90 <module>) Using main config from conf/default.yml
2021-01-05 13:28:45 - ERROR (app_svc.py:153 validate_requirement) go does not meet the minimum version of 1.11
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: debrief
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: atomic
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: stockpile
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: compass
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: sandcat
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: gameboard
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: fieldmanual
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: training
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: manx
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: response
2021-01-05 13:28:45 - INFO  (app_svc.py:107 load) Enabled plugin: access
2021-01-05 13:28:45 - ERROR (c_plugin.py:94 _load_module) Error importing plugin=atomiccaldera, No module named 'app.utility.logger'
2021-01-05 13:28:45 - ERROR (c_plugin.py:60 load_plugin) EError loading plugin=atomiccaldera, 'NoneType' object has no attribute 'description'
2021-01-05 13:28:48 - INFO  (hook.py:58 build_docs) Docs built successfully.
2021-01-05 13:28:49 - INFO  (server.py:58 run_tasks) All systems ready.
===========================================

In /opt/caldera/plugins/atomiccaldera/app/atomic_caldera.py the problematic line is "from app.utility.logger import Logger", if you comment it, the error disappear.

The file /opt/caldera/app/utility/logger.py don't exists, thus, It can load the library 

Same problem with /opt/caldera/plugins/atomiccaldera/hook.py from app.database.core_dao import CoreDao

The quetion is, whe are these files?

Thanks.

**Comment by faurkaurage** [comment]
Has there been any fix to this issue? There are not many resources online about atomic-caldera. I would love to see a Youtube guide going through installation and use at a basic level. 

Questions:

1. After following the installation guide, do I go to the /legacy folder and run the atomic-caldera.py program 
2. Also, when I run caldera without '--insecure' it does not load. I'm assuming running caldera without --insecure creates the local.yml file? What do I need to change in that for Caldera to run?   

Sorry for the dumb questions, noob here

Looking Forward
